In [6]:
import statsmodels.api as sm

In [1]:
import numpy as np

In [2]:
x = np.random.rand(10)
y =10*x +20

In [3]:
x

array([ 0.38958841,  0.1832779 ,  0.44927798,  0.40825398,  0.41630235,
        0.25800875,  0.10679327,  0.07731843,  0.85777738,  0.48046451])

In [4]:
y

array([ 23.89588412,  21.83277897,  24.49277977,  24.08253978,
        24.16302347,  22.58008752,  21.06793274,  20.77318435,
        28.57777381,  24.80464506])

In [8]:
sm.OLS(y, sm.add_constant(x)).fit().params

array([ 20.,  10.])